# Generated by Django 3.0.6 on 2020-05-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200518_0705"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="pref_categories",),
    ]
