# Generated by Django 3.0.6 on 2020-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=155, unique=True, verbose_name="Category name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        verbose_name="Category slug(from name)",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name_plural": "Categories", "ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Comment text")),
                ("image", models.TextField(blank=True, verbose_name="Comment image")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["text"],},
        ),
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Land title(size + size_type + in + location)",
                    ),
                ),
                (
                    "cost",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cost of land"
                    ),
                ),
                (
                    "for_type",
                    models.CharField(
                        choices=[("FR", "for free"), ("LE", "for leasing")],
                        default="LE",
                        max_length=30,
                        verbose_name="Land listing type(free or rent)",
                    ),
                ),
                ("size", models.CharField(max_length=30, verbose_name="Land size")),
                (
                    "size_type",
                    models.CharField(
                        choices=[
                            ("M", "metres"),
                            ("KM", "kilometres"),
                            ("ML", "miles"),
                        ],
                        default="M",
                        max_length=30,
                        verbose_name="Land size measurement type",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Land location"),
                ),
                (
                    "images",
                    models.TextField(blank=True, verbose_name="Images of the land"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PR", "private"), ("PU", "public")],
                        default="PU",
                        max_length=30,
                        verbose_name="Visible to",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["title"],},
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="List title")),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description of the List"
                    ),
                ),
                (
                    "cover_image",
                    models.TextField(blank=True, verbose_name="Cover image"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PR", "private"), ("PU", "public")],
                        default="PU",
                        max_length=30,
                        verbose_name="Visible to",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["title"],},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Post title")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, verbose_name="Post slug(from title)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description of the post"
                    ),
                ),
                ("images", models.TextField(blank=True, verbose_name="Post images")),
                (
                    "video_link",
                    models.TextField(blank=True, verbose_name="Post video link"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PR", "private"), ("PU", "public")],
                        default="PU",
                        max_length=30,
                        verbose_name="Visible to",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["title"],},
        ),
    ]
