# Generated by Django 3.0.6 on 2020-05-11 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author linked to",
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="posts",
            field=models.ManyToManyField(
                blank=True, to="resources.Post", verbose_name="Posts of list"
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author linked to",
            ),
        ),
        migrations.AddField(
            model_name="land",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author linked to",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.Post",
                verbose_name="Post linked to",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author linked to",
            ),
        ),
    ]
