# Generated by Django 3.0.6 on 2020-05-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_auto_20200520_0825"),
    ]

    operations = [
        migrations.RemoveField(model_name="land", name="images",),
    ]
