# Generated by Django 3.0.6 on 2020-05-20 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0004_remove_land_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="land", old_name="size_type", new_name="size_unit_measurement",
        ),
        migrations.AlterField(
            model_name="land",
            name="cost",
            field=models.FloatField(
                blank=True, max_length=100, verbose_name="Cost of land"
            ),
        ),
        migrations.AlterField(
            model_name="landimage",
            name="uploaded_for",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="land_images",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Land Linked to",
            ),
        ),
    ]
