# Generated by Django 3.0.6 on 2020-05-20 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0008_auto_20200520_1800"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="user", new_name="created_by",
        ),
        migrations.RemoveField(model_name="post", name="images",),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.Category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="land",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="landimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="land_image_uploads/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="Post slug(from title)"
            ),
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="post_image_uploads/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "upload_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Post Linked to",
                    ),
                ),
            ],
        ),
    ]
