# Generated by Django 3.0.6 on 2020-05-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_auto_20200520_2138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="land",
            name="size",
            field=models.FloatField(verbose_name="Land size"),
        ),
    ]
