# Generated by Django 3.0.6 on 2020-05-21 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0012_auto_20200521_0840"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landimage",
            name="upload_for",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="land_images",
                to="resources.Land",
                verbose_name="Land Linked to",
            ),
        ),
        migrations.AlterField(
            model_name="listpost",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="resources.List",
            ),
        ),
        migrations.AlterField(
            model_name="listpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="resources.Post",
            ),
        ),
        migrations.AlterField(
            model_name="listpost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="upload_for",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_images",
                to="resources.Post",
                verbose_name="Post Linked to",
            ),
        ),
    ]
