# Generated by Django 3.0.6 on 2020-05-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0015_auto_20200521_2346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="land",
            name="lease_rate_periodicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("h", "hourly"),
                    ("d", "daily"),
                    ("w", "weekly"),
                    ("m", "monthly"),
                    ("y", "yearly"),
                ],
                max_length=10,
                verbose_name="Lease Rate Periodicity",
            ),
        ),
    ]
