# Generated by Django 3.0.6 on 2020-05-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0016_auto_20200521_2347"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="user", new_name="created_by",
        ),
        migrations.RemoveField(model_name="comment", name="image",),
        migrations.AddField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.Comment",
                verbose_name="reply",
            ),
        ),
        migrations.CreateModel(
            name="CommentImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="comment_image_uploads/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "upload_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_images",
                        to="resources.Post",
                        verbose_name="Comment Linked to",
                    ),
                ),
            ],
        ),
    ]
